### ISSUE TITLE
The *.desktop file is lacking a Categories= entry

### ISSUE THREAD

**Issue by probonopd** [huxingyi/dust3d#12]
The `*.desktop` file is lacking a `Categories=` entry.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

__electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).__. Please see the `category` key at https://www.electron.build/configuration/linux-other.

References: 
* https://github.com/AppImage/appimage.github.io/issues/2
* https://github.com/AppImage/appimage.github.io/pull/645

**Comment by huxingyi** [comment]
Thank you, will fix it by today.

**Comment by huxingyi** [comment]
Hi, I have fixed the desktop file, added [ubuntu screenshot](https://raw.githubusercontent.com/huxingyi/dust3d/master/ci/screenshot.png) and appdata.xml by following the checklist of https://github.com/AppImage/appimage.github.io in this commit c632b8b

if there is anything I can do to match better with AppImage, please let me known, thanks in advance.
BTW, forgot to say, AppImage is really cool!

**Comment by probonopd** [comment]
Thank you very much @huxingyi. Please let me know once the new AppImage can be downloaded from https://github.com/huxingyi/dust3d/releases so that I can test it. Keep up your great work!

**Comment by huxingyi** [comment]
Hi, @probonopd thanks, the new AppImage is ready: https://github.com/huxingyi/dust3d/releases/download/unstable/dust3d_unstable-x86_64.AppImage

> released this on Apr 14 · 93 commits to ed7d8793117d12ce11870463f93ac204738bf731 since this release

The info shows on the release page is not get updated, GitHub only update this timestamp when the tag is first been created. However, the binaries are been replaced from CI on every git push.

Because there are planned new features (Animation Clips Generation) haven't been finish yet, so the latest release would keep on unstable for a while until the 1.0 version been released.

**Comment by probonopd** [comment]
Getting

`AppRun: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version 'CXXABI_1.3.8' not found (required by /run/firejail/appimage/.appimage-6903/AppRun)`

Please see https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#creating-appimages-that-are-compatible-with-many-systems and especially https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#libstdcso6. Thank you very much for your consideration.

**Comment by huxingyi** [comment]
Hi, @probonopd I have made the [AppImage](https://github.com/huxingyi/dust3d/releases/download/unstable/dust3d_unstable-x86_64.AppImage) which runs on Ubuntu 14.04, 16.04, however it cannot run on CentOS 6.8 because of too old libc. I build it using Travis CI in trusty Ubuntu 14.04.5 LTS with gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

I may invest more time to build it on an older system such as CentOS 6.8 using Travis CI with docker in the future after I finish the planned features of the software.

**Comment by probonopd** [comment]
Thank you very much, it is working 👍 I added it to the AppImageHub directory of available AppImages. Keep up your great work!
