### ISSUE TITLE
Exporting .obj fails on Mac

### ISSUE THREAD

**Issue by RubenSandwich** [huxingyi/dust3d#20]
Exporting to OBJ fails silently for me on OS X.

I'm using OS X Mojave 10.14.1 and dust3d 1.0.0 beta 6 with this simple palm tree model. (I added .txt to the file to upload it here, just remove it use it.)

[tree.ds3.txt](https://github.com/huxingyi/dust3d/files/2636466/tree.ds3.txt)

**Comment by huxingyi** [comment]
Hi, thanks for reporting. If the rendered model disappear, that means the mesh combination failed, you need adjust the node positions or make separate parts instead of as a whole part.

I adjust a little, and I can export obj no problem when I can see the generated model, please see the following gif:
![dec-02-2018 10-10-42](https://user-images.githubusercontent.com/3941597/49334329-aa354300-f61a-11e8-83c1-2e20418f60fa.gif)

**Comment by RubenSandwich** [comment]
Oh okay, thanks. Mind having some sort of interface element that lets me know that the model generation failed? (It'd also be nice to move the model preview window around.) So far I'm enjoying how easy simple modeling is with dust3d.

**Comment by huxingyi** [comment]
Currently, if the model preview disappear, that means the generation failed. If you can see it, that means the visible parts are good, if some parts missing, there need some adjustment.

Use middle mouse button + shift key to move the model preview window.
Enjoy!

**Comment by RubenSandwich** [comment]
Yeah, I understand that if the model generation fails the window is empty. I'm asking for a less subtle indicator. Like "Model Generation Failed" in the model preview window and a reason why. Anyway, I'm closing this issue. Thanks again.
