### ISSUE TITLE
AppImage does not run on CentOS 7.6

### ISSUE THREAD

**Issue by Chaz6** [huxingyi/dust3d#27]
The AppImage is based on glibc 2.18 however CentOS provides glibc 2.17. It gives the following output:-

```
dust3d: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /tmp/.mount_dust3d6NIN06/usr/lib/libmeshlite_ffi.so)
```

**Comment by huxingyi** [comment]
Currently, the AppImage is been generated on the Ubuntu trusty from Travis CI. And glibc 2.18 is the minimum requirement. Change the build system of Travis CI may broke other things. And RedHat 8 Beta is on the way, I guess CentOS 8 should be not far away, which comes with glibc 2.18.

So, for the current stage, no AppImage for CentOS 7 provided, however, you can still build on your own by following this [build](http://docs.dust3d.org/en/latest/builds.html) guide, please refer to the Ubuntu section, most of the install commands should be the same instead of replacing the apt-get to yum. Pull request on adding the build instructions of CentOS to the [document](https://github.com/huxingyi/dust3d/blob/master/docs/builds.rst) is VERY welcome and appreciated.
Thanks!

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
