### ISSUE TITLE
[REQUEST] extra export options

### ISSUE THREAD

**Issue by lewislepton** [huxingyi/dust3d#43]
again, great software. fantastic & fast. but extra export options would be nice.

I had to use blender for a simple tutorial I was making, in which I needed several different file formats to show them loading into a project. but it would be nice if dust3d had extra export options

such as these ones from blender [screenshot below]. im not saying all of these would be nice, but some extra formats would be great, more so because of peoples preferences. though I do know `.fbx` is in the options already.
if not thats fine, but just more so asking 😉 

<img width="235" alt="Screenshot 2019-08-28 at 13 51 22" src="https://user-images.githubusercontent.com/11299322/63857176-25096f80-c99b-11e9-8792-20b8f0044130.png">

thanks again for this great software. can't wait to dive in further & get some nice models made for my own projects & even teachings 😉

**Comment by huxingyi** [comment]
Thanks for the suggestions, currently supported formats in Dust3D: .obj/.glb/.fbx
I hope the .glb will become a de facto standard in the coming years.

For the currently supported formats:
**.obj** is for export the quad mesh, so you can further edit the mesh in other software, such as blender
**.glb** Unreal engine has a built-in plugin to support importing glb, but currently need user to manually enable it (glTF). Godot engine supports importing glb. It's becoming a well adopted standard.
**.fbx** Unity engine and Unreal engine supports importing fbx.

Currently, there is not enough manpower to support more formats, because introducing a new format itself need tons of coding, and most importantly, it adds extra consideration of each format when new features been introduced.

**Comment by lewislepton** [comment]
that's great to know. thanks for saying what's happening.
aye, I figured it was more people power & obviously plenty of coding is needed to get such a thing.

thank again for creating this great software 😽

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
