### ISSUE TITLE
Slow, choppy 3d model view manipulation

### ISSUE THREAD

**Issue by panbeep** [huxingyi/dust3d#57]
3d model manipulation is slow and choppy. It freezes constantly when trying to move, rotate or zoom the generated 3d model. 
My PC specs are:
System: Windows 10
CPU: i7 8700k
GPU: RTX 2080
RAM: 64GB

**Comment by huxingyi** [comment]
Hi @panbeep thanks for the feedback. Currently the zoom may have a little bit lag behind (Know issue), but move, rotate should be ok? Would you mind record your screen for seconds to show please? Also if provide the .ds3 file would be much appreciated.

**Comment by panbeep** [comment]
Hi @huxingyi 
here is the screen recording. You can notice it reacts to the mouse commands with quite long period.
https://www.dropbox.com/s/wqy0ztowt9zm4xh/dust_3d_choppy_movement.mp4?dl=0

**Comment by huxingyi** [comment]
Thanks for the video, looks weird, don't know the reason yet, BTW, are you using the 1.0.0-rc.1 version? looks like you are using an old version? because the latest one don't have the dog-head example model. Could you try the latest version and see if it's still slow, also please try the mosquito model, to see if only this model get slow down. Thanks!

**Comment by huxingyi** [comment]
Also, are you open another 3D software at the same time? such as blender? There maybe some conflicts in the opengl driver when you open multiple opengl heavy processes at the same time.

**Comment by panbeep** [comment]
I tried latest 1.0.0-rc.1 version and it works fine with it. Thanks for pointing me to the right direction.

**Comment by huxingyi** [comment]
Good to hear it works now. I am closing this, please feel free to reopen it or create a new issue if there is still problem. Thanks!
