### ISSUE TITLE
weird Symmetry ?

### ISSUE THREAD

**Issue by xtvjxk123456** [huxingyi/dust3d#6]
the symmetry function is incomplete? 
it is different from what I think.

**Comment by huxingyi** [comment]
There is only x-axis-mirror, and you can adjust the mirror center by manipulate the triangle.
if the generated mesh is not good, you can also align the nodes to center from the context menu(Select the nodes first).
The mirror function is a rough version currently, could you give more details about what you think it should like please? Thanks.

**Comment by xtvjxk123456** [comment]
Mmmmm, The mirror function is interesting, but not Efficient, I like common 3d software displaying axis origin better.I will try to master the mirror function in dust3d

**Comment by huxingyi** [comment]
You are right, if there is a feeling, that something is not efficient or smooth, there must be some potential improvement.

**Comment by huxingyi** [comment]
Hi, @xtvjxk123456 sorry for the delay fix.
I think I didn't aware the issue you first mentioned, because I usually test Dust3D with a turnaround reference sheet background image.
I just found the symmetry not work without a background image because of a coord calculate bug, in that case, you will not see the symmetry anchor, a triangle, so you would not able to adjust the mirror center.
I have fixed it.
Could you make sure if it is the issue you first mentioned please? thanks.

**Comment by xtvjxk123456** [comment]
great work, the program becomes more stable

**Comment by huxingyi** [comment]
Hi, I am closing this now, if you still have symmetry issues with the latest version, please feel free to reopen it.
