### ISSUE TITLE
Ability to change mirror plane for parts

### ISSUE THREAD

**Issue by hikari-no-yume** [huxingyi/dust3d#95]
Hello. This is a cool project!

The first thing I tried to make with it:

![Spider-like creature with four legs, each pointing a different cardinal](https://user-images.githubusercontent.com/579774/97079539-0d586600-15f5-11eb-95cc-dc787a58e951.png)

As is hopefully clear from the image, this creature has four legs, one pointing in each cardinal direction on the horizontal plane.

When I drew the first leg, I used the “mirror” (⚖️) button on the part to turn it into two legs.

But when I wanted to make the third and fourth legs, it seems you can't change what the mirror plane is for a part, so I couldn't use the mirror feature for them. Instead I had to create separate parts.

So it might be a nice enhancement if you can change, for an individual part, what mirror plane is used.

By the way, if this feature is really not there right now, I might try to add it myself. (EDIT: I would like to but it seems like a lot of hassle to get a C++ project like this to build…)

**Comment by huxingyi** [comment]
The mirror is on x-axis only (Front view) currently, you can copy, paste and move the part nodes to easily create another part.
Your idea of adding mirror plane is great, however, since the mirror toggle it's related with rig and motion generation, and the rig and motion feature are been refactoring, so we can consider add the mirror plane maybe after the rig and motion feature been stablized. Thanks.

**Comment by hikari-no-yume** [comment]
By the way, a similar feature that might be nice would be rotational symmetry. If someone wants to create a flower, for example, it would be useful. This could probably be accomplished with a script though.

**Comment by huxingyi** [comment]
Closed as not relevant to the latest release anymore, thanks and feel free to reopen it.
